version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /gunicorn.sh
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8081:8000"
    volumes:
      - media:/app/media

  postgres:
    image: postgres:13.4
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=project
      - POSTGRES_DB=project
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2.5-alpine3.14
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

  memcached:
    image: memcached:1.6.10-alpine
    ports:
      - "11211:11211"

volumes:
  postgres: { }
  redis: { }
  media: { }
