import os

from .common import REDIS_HOST
from .common import TIME_ZONE

BROKER_URL = CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL') or 'redis://{}/0'.format(REDIS_HOST)
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 172800}

CELERY_SEND_TASK_ERROR_EMAILS = False
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'

CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE

CELERY_WORKER_SEND_TASK_EVENTS = True
CELERY_EVENT_QUEUE_TTL = 10
CELERY_EVENT_QUEUE_EXPIRES = 600

CELERY_BROKER_TRANSPORT_OPTIONS = {
    'visibility_timeout': 18000,
}
